# Variables to control Makefile operation

CXX = gcc
CXXFLAGS = -O3

# ****************************************************
# Targets needed to bring the executable up to date

hidden_binary: hidden_binary.c
	$(CXX) -o hidden_binary hidden_binary.c
